version: "3.0"

services:
  master:
    image: mongo:4.0.1
    command: mongod --replSet rs1
    volumes:
      - ./mongo_data:/data/db/
    ports:
      - "27017:27017"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 2s
      timeout: 2s
      retries: 5
  slave:
    image: mongo:4.0.1
    command: mongod --replSet rs1
    ports:
      - "27018:27017"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mongo"]
      interval: 2s
      timeout: 2s
      retries: 5
  conf:
    image: mongo:4.0.1
    volumes:
      - ./scripts:/scripts
    command: bash /scripts/conf.sh
    depends_on:
      - master
      - slave
  backup:
    image: mongo:4.0.1

