version: "3"

services:
  master:
    image: mongo:4.0.1
    command: mongod --config /etc/mongo_conf/mongo.cnf
    volumes:
      - ./mongo_conf:/etc/mongo_conf
    ports:
      - "27017:27017"
    restart: always
  slave:
    image: mongo:4.0.1
    command: mongod
    ports:
      - "27018:27017"
    restart: always
#  conf:
#    image: mongo:4.0.1
#    command: mongo mongodb://master:27017 --eval="rs.initiate(); rs.add('slave');"
#    depends_on:
#      - master
#      - slave

